config/routes.rb
Rails.application.routes.draw do


  get '/home' => 'sittings#select_sitting'
   # post '/home' => 'sittings#select_sitting'

  mount Upmin::Engine => '/admin'

  devise_for :users, :controllers => { registrations: 'users/registrations' }

  # devise_scope :user do
  # 	root :to => "devise/sessions#new"
  # end

  devise_scope :user do
    authenticated :user do
      root 'sittings#select_sitting', as: :authenticated_root
      # match '/sessions/user', to: 'devise/sessions#create', via: :post
    end

    unauthenticated do
      # root 'devise/sessions#new', as: :unauthenticated_root
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

 # users
  get "users/new" => "users#new", as: :users_new_user
  post "users/create_user" => "users#create", as: :users_create_user
  get "users/:id/edit" => "users#edit", as: :users_edit_user
  put "users/:id" => "users#update", as: :users_update_user

 # calendars/google authenication
  resources :calendars
  get "/auth/:provider/callback" => 'calendars#create'
  post "/calendars" => 'calendars#new'

  #sittings

  get '/sittings/refresh' => 'sittings#refresh'
  post '/sittings/refresh' => 'sittings#refresh'
  # get '/sittings/create_calendar'  => 'sittings#create_calendar'
  get '/sittings/update_calendar'  => 'sittings#update_calendar'
  get '/sittings/select_sitting'  => 'sittings#select_sitting'
  post '/sittings/select_sitting'  => 'sittings#select_sitting'
  post '/sittings/update_sitting' => 'sittings#update_sitting'
  get '/sittings/update_sitting' => 'sittings#update_sitting'
  post '/sittings/update' => 'sittings#update'
  post '/sittings/view_past_sittings' => 'sittings#view_past_sittings'
  get '/sittings/view_past_sittings' => 'sittings#view_past_sittings'


  #clients
  delete '/clients/:clients_sittings_id/cancel_attendance' => 'clients#cancel_attendance'
  post '/clients/attendance/' => 'clients#attendance'
  get '/clients/attendance', to:'clients#attendance'
  get '/clients/list_all' => 'clients#list_all'
  post '/clients/list_all' => 'clients#list_all'
  post '/clients/update_list_all_client' => 'clients#update_list_all_client'
  post '/clients/update_clients_sitting_autocomplete' => 'clients#update_clients_sitting_autocomplete'
  post '/clients/update_client_status' => 'clients#update_client_status'
  get '/clients/autocomplete', to: 'clients#autocomplete', as: 'autocomplete_client'
  # post '/clients/js_add_client_to_sitting', to: 'clients#js_add_client_to_sitting'
  get 'clients/home' => 'clients#home'
  get '/clients/schedule_meetings' => 'clients#schedule_meetings'
  post '/clients/schedule_meetings' => 'clients#schedule_meetings'
  get '/clients/:group_id/new_dropdown' =>'clients#new_dropdown'
  post '/clients/new_dropdown' =>'clients#new_dropdown'
  get '/clients/manage_clients' => 'clients#manage_clients'
  post '/clients/manage_clients' => 'clients#manage_clients'
  get '/clients/manage_inactive_clients' => 'clients#manage_inactive_clients'
  post '/clients/manage_inactive_clients' => 'clients#manage_inactive_clients'
  get '/clients/manage_absent_clients' => 'clients#manage_absent_clients'
  post '/clients/manage_absent_clients' => 'clients#manage_absent_clients'
  post '/clients/new' => 'clients#new'
  get  'clients/:id/history' => 'clients#history'
  post '/clients/:id/history' => 'clients#history'
  post '/clients/:id/edit' => 'clients#edit'
  post '/clients/:id/update' => 'clients#update'
  patch '/clients/:id/update' => 'clients#update'
  get '/clients/update' => 'clients#update'
  post '/clients/update' => 'clients#update'

  #special_status
  get '/clients/:client_id/new_special_status' => 'clients#new_special_status'
  post '/clients/update_special_status' => 'clients#update_special_status'

  #location
  post '/clients/update_location_status' => 'clients#update_location_status'

  #meetings
  post '/meetings/:meeting_id/delete_other_meeting' => 'meetings#delete_other_meeting'
  delete '/meetings/:meeting_id/delete_other_meeting' => 'meetings#delete_other_meeting'
  post '/meetings/:meeting_id/edit_other_meeting' => 'meetings#edit_other_meeting'
  get '/meetings/:meeting_id/edit_other_meeting' => 'meetings#edit_other_meeting'
  get '/meetings/:client_id/new' => 'meetings#new'
  post '/meetings/update' => 'meetings#update'
  delete '/meetings/:meeting_id/destroy' => 'meetings#destroy'
  post '/meetings/new_other_meeting' => 'meetings#new_other_meeting'
  get '/meetings/new_other_meeting' => 'meetings#new_other_meeting'
  get '/meetings/autocomplete', to: 'meetings#autocomplete', as: 'autocomplete_meeting'
  get '/meetings/show_other' => 'meetings#show_other'
  post '/meetings/show_other' => 'meetings#show_other'

  #groups
  delete '/groups/:clients_groups_id/delete_clients_groups' => 'groups#delete_clients_groups'
  delete '/groups/:id/delete_group' => 'groups#delete_group'
  get '/groups/:id/all_clients_in_group' => 'groups#all_clients_in_group'
  post '/groups/manage_groups' => 'groups#manage_groups'
  get '/groups/manage_groups' => 'groups#manage_groups'
  post '/groups/update_clients_in_group' => 'groups#update_clients_in_group'
  post '/groups/new' => 'groups#new'
  post '/groups/:id/edit' => 'groups#edit'
  get '/groups/:id/update' => 'groups#update'
  post '/groups/:id/update' => 'groups#update'
  patch '/groups/:id/update' => 'groups#update'
  get '/groups/update' => 'groups#update'
  post '/groups/update' => 'groups#update'

  #notes
  post '/notes/new' => 'notes#new'
  get '/notes/update' => 'notes#update'
  post '/notes/update' => 'notes#update'
  post '/notes/:id/edit' => 'notes#edit'
  delete '/notes/:id/destroy' => 'notes#destroy'

  #reports
  get 'reports/generate_reports' => 'reports#generate_reports'
  post 'reports/generate_reports' => 'reports#generate_reports'
  post 'reports/new' => 'reports#new'
  get 'reports/attendance_report' => 'reports#attendance_report'
  post 'reports/attendance_report' => 'reports#attendance_report'
  get 'reports/meeting_report' => 'reports#meeting_report'
  post 'reports/meeting_report' => 'reports#meeting_report'
  get 'reports/client_report' => 'reports#client_report'
  post 'reports/client_report' => 'reports#client_report'


  # resources :sessions
  # resources :users
  resources :reports
  resources :clients
  resources :meetings
  resources :monastics
  resources :sittings
  resources :clients_sittings
  resources :attendance_status_types
  resources :groups
  resources :notes

  get '/visitors/instructions' => 'visitors#instructions'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  has_one :clients_sitting
  belongs_to :manager
  has_many :notes
  belongs_to :client
  belongs_to :meeting_types
  belongs_to :partner
end

app/models/meeting_type.rb
class MeetingType < ActiveRecord::Base
  has_many :meetings
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  # MEETING METHODS
  def new
    @sitting_id = session[:sitting_id]
    @sitting_start_date = Sitting.find(@sitting_id).start_date
    @sitting_start_time = Sitting.find(@sitting_id).start_time
    @client_id = params[:client_id]
    @client = Client.find(@client_id)
    @meeting = Meeting.new
    @regular_meeting_type = MeetingType.where(name:"regular").first.id
    @attendance_status_type_id_present = AttendanceStatusType.where(name: "present").first.id
    @show_meetings = Meeting.select('meetings.start_date, meetings.client_id, sittings.event_title AS event_title, managers.initials AS initials').joins('
      INNER JOIN clients ON clients.id = meetings.client_id
      LEFT OUTER JOIN managers ON managers.id = meetings.manager_id
      LEFT OUTER JOIN sittings ON sittings.id = meetings.sitting_id'
      ).where("
      meetings.client_id =? AND meetings.start_time !=?", @client, @sitting_start_time).order("start_date DESC").limit(10)
    @show_attendance = ClientsSitting.select('clients_sittings.client_id, sittings.event_title AS event_title, sittings.start_date AS start_date, attendance_status_types.id AS attendance_status_type').joins('
    LEFT OUTER JOIN sittings ON sittings.id = clients_sittings.sitting_id
    LEFT OUTER JOIN attendance_status_types ON attendance_status_types.id = clients_sittings.attendance_status_type_id'
    ).where("
    clients_sittings.client_id =? AND sittings.start_time !=? AND clients_sittings.attendance_status_type_id=?", @client, @sitting_start_time, @attendance_status_type_id_present).order("start_date DESC").limit(10)
  end

  def update
    meeting = Meeting.where(client_id:params[:meeting][:client_id], manager_id:params[:meeting][:manager_id], meeting_type_id:params[:meeting][:meeting_type_id]).first_or_initialize
      meeting = params[:meeting]
      start_date_params = Date.new meeting["start_date(1i)"].to_i, meeting["start_date(2i)"].to_i, meeting["start_date(3i)"].to_i
      m = Meeting.where(start_date:start_date_params, start_time:start_date_params, client_id:params[:meeting][:client_id], manager_id:params[:meeting][:manager_id], meeting_type_id:params[:meeting][:meeting_type_id]).first_or_initialize
      respond_to do |format|
        if (m.update(meeting_params))
          format.html { redirect_to("/meetings/show_other") }
        else
          format.html { redirect_to("/meetings/show_other") }
        end
      end
  end

  def destroy
    clients_sitting = ClientsSitting.where(meeting_id:params[:meeting_id]).first_or_initialize
    clients_sitting.meeting = nil
    clients_sitting.save
    meeting = Meeting.find(params[:meeting_id])
    meeting.destroy
    redirect_to '/clients/schedule_meetings/'
  end

  def show_other
    @other_meetings = Meeting.select('meetings.start_date, meetings.client_id, meetings.id, meetings.meeting_type_id, meetings.duration, clients.first_name AS first_name, clients.last_name AS last_name, managers.id AS manager_id, managers.title AS manager_title, managers.first_name AS manager_first_name, managers.last_name AS manager_last_name').joins('
      INNER JOIN clients ON clients.id = meetings.client_id
      LEFT OUTER JOIN managers ON managers.id = meetings.manager_id'
      ).order("start_date DESC")
  end

  def new_other_meeting
    @other_meeting = Meeting.new
  end

  def autocomplete
    @clients = Client.search_by_name(params[:term]).active_client
    render json: @clients, root: false, each_serializer: AutocompleteSerializer
  end

  def edit_other_meeting
    @other_meeting = Meeting.find(params[:meeting_id])
    @client_id = @other_meeting.client_id
    @client = Client.find(@client_id)
  end

  def delete_other_meeting
    @other_meeting = Meeting.find(params[:meeting_id])
    @other_meeting.destroy
    respond_to do |format|
      format.html { redirect_to '/meetings/show_other' }
      format.json
      format.js
    end
  end

  private
    def meeting_params
      params.require(:meeting).permit(:manager_id, :note_id, :sitting_id, :client_id, :start_date, :start_time, :meeting_type_id, :partner_id, :duration)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper

end

app/views/meetings/_other_meeting_form.html.erb
<%= form_for(@other_meeting, :url=>{:action=>"update"}) do |f| %>
   <div class="field">
      <%= f.hidden_field :sitting_id, :value => nil%>
      <%= f.hidden_field :meeting_type_id, :value => @other_meeting_type%>
   </div>
   <div class="field col-xs-3">
      <%= f.label :client_id, "Client" %>
      <%= autocomplete_field_tag('Name', '', autocomplete_meeting_path, :id_element => "#meeting_client_id", class: "form-control", id:"name-search-autocomplete") %>
      <%= f.hidden_field :client_id%>
   </div>
   <div class="field col-xs-12">
      <%= f.label :start_date, "Meeting Date" %>
      <%= f.date_select :start_date %>
   </div>
   <div class="field col-xs-12">
      <%= f.label :partner_id, "Partner (if Applicable)" %>
      <%= f.collection_select(:partner_id, Partner.all, :id, :org_name, {:class =>'form-control'}) %>
   </div>
   <div class="field col-xs-12">
      <%= f.label :manager_id, "Case Manager" %>
      <%= f.collection_select(:manager_id, Manager.all, :id, :manager_name, {:class =>'form-control'}) %>
   </div>
   <div class="field col-xs-12">
      <%= f.label :meeting_type_id, "Activity Type" %>
      <%= f.collection_select(:meeting_type_id, MeetingType.all, :id, :name, {:class =>'form-control'}) %>
   </div>
   <div class="field col-xs-12">
      <%= f.label :duration, "Duration" %>
      <%= f.text_field :duration %>
   </div>
   <div id= "buttonId" class="actions col-xs-12 text-left">
      <%= f.submit "Submit", class:"btn btn-default btn-xs" %>
   </div>
<%end%>

app/views/meetings/edit_other_meeting.html.erb
<div class="container-fluid">
   <div id="links" class="row col-xs-8">
     <%= button_to('Back', meetings_show_other_path, :class => 'btn btn-primary pull-right btn-padded')  %>
   </div>
   <div class="row col-xs-8">
      <h2> Meeting information </h2>
      <div class="field col-xs-12">
         <span class="form-edits">Client:</span>
         <span class="form-edits-s"><%=display_name%></span>
      </div>

      <%= form_for(@other_meeting, :url=> {:action=> "update" }) do |f| %>

        <div class="field">
          <%= f.hidden_field :sitting_id, :value => nil%>
          <%= f.hidden_field :meeting_type_id, :value => @other_meeting_type%>
       </div>
       <div class="field col-xs-3">
          <%= f.hidden_field :client_id%>
       </div>
       <div class="field col-xs-12">
          <%= f.label :start_date, "Meeting Date" %>
          <%= f.date_select :start_date %>
       </div>
       <div class="field col-xs-12">
          <%= f.label :partner_id, "Partner (if Applicable)" %>
          <%= f.collection_select(:partner_id, Partner.all, :id, :org_name, {:class =>'form-control'}) %>
       </div>
       <div class="field col-xs-12">
          <%= f.label :manager_id, "Case Manager" %>
          <%= f.collection_select(:manager_id, Manager.all, :id, :manager_name, {:class =>'form-control'}) %>
       </div>
       <div class="field col-xs-12">
          <%= f.label :meeting_type_id, "Activity Type" %>
          <%= f.collection_select(:meeting_type_id, MeetingType.all, :id, :name, {:class =>'form-control'}) %>
       </div>
       <div class="field col-xs-12">
          <%= f.label :duration, "Duration" %>
          <%= f.text_field :duration %>
       </div>
       <div id= "buttonId" class="actions col-xs-12 text-left">
          <%= f.submit "Submit", class:"btn btn-default btn-xs" %>
       </div>
      <%end%>
   </div>
</div>

app/views/meetings/new.html.erb
<div class="container-fluid">
   <div class="col-xs-12 col-md-8">
      <div id= "links" class="actions">
         <%= button_to('Back', clients_schedule_meetings_path, :class => 'btn btn-primary pull-right btn-padded')%>
      </div>
   </div>
   <div class="col-xs-12 col-md-8">
      <table class="table table-condensed">
         <thead>
            <tr class="noborder">
               <th colspan="2"><h3>New Meeting</h3></th>
            </tr>
            <tr>
               <th class="norm">Name</th>
               <th class="norm">To be seen by</th>
            </tr>
         </thead>
            <tr>
               <td class="norm">
                  <%=display_name%>
               </td>
               <td>
                  <%= form_for(@meeting, :url=>{:action=>"update"},:html => {
                     :class =>"select_client_group_form"}) do |f| %>
                     <div class="field">
                         <%= f.hidden_field :sitting_id, :value => @sitting_id %>
                         <%= f.hidden_field :client_id, :value => @client_id %>
                         <%= f.hidden_field :start_date, :value => @sitting_start_date %>
                         <%= f.hidden_field :start_time, :value => @sitting_start_time %>
                         <%= f.hidden_field :meeting_type_id, :value => @regular_meeting_type%>
                         <%= f.collection_select(:manager_id, Manager.all, :id, :manager_name, {:class =>'form-control'}) %>
                     </div>
                     <div id= "buttonId" class="actions col-xs-6 text-left">
                         <%= f.submit "Submit", class:"btn btn-default btn-md center-block" %>
                     </div>
                  <%end%>
               </td>
             </tr>
         <thead>
            <tr class="noborder">
               <th colspan="2"><h3>Past meetings</h3>
            </tr>
            <tr>
               <th class="norm"> Sitting </th>
               <th class="norm"> Manager </th>
            </tr>
         </thead>
            <% @show_meetings.each do |meeting| %>
               <tr>
                  <% if @show_meetings != nil %>
                     <%if meeting.start_date!= nil%>
                        <td class="norm"><%=meeting.start_date.strftime("%A, %B %-d, %Y")%>
                     <%end%>
                     <%if meeting.event_title!= nil%>
                        <%= " - " + meeting.event_title %></td>
                     <%end%>
                     <%if meeting.initials!= nil%>
                        <td class="norm"><%=meeting.initials%></td>
                     <%end%>
                   <%end%>
               </tr>
            <%end%>
         <thead>
            <tr class="noborder">
               <th colspan="2"><h3>Recently attended sittings</h3>
            </tr>
            <tr>
             <th class="norm"> Date</th>
             <th class="norm"> Sitting </th>
             <th></th>
            </tr>
         </thead>
            <%if @show_attendance.length > 0%>
               <% @show_attendance.each do |attendance| %>
                  <tr>
                  <%if attendance.start_date != nil%>
                     <td class="norm"><%=attendance.start_date.strftime("%A, %B %-d, %Y")%></td>
                  <%end%>
                  <%if attendance.event_title != nil%>
                     <td class="norm"><%=attendance.event_title%></td>
                  <%end%>
                     <td></td>
                  </tr>
               <%end%>
            <%end%>
      </table>
   </div>
</div>

app/views/meetings/new_other_meeting.html.erb
<div class="container-fluid">
   <div class="col-xs-12 col-md-8">
      <div id= "links" class="actions">
          <%= button_to('Back', sittings_select_sitting_path, :class => 'btn btn-primary pull-right btn-padded')%>
      </div>
   </div>
   <div class="col-xs-12">
      <h3>New Activity</h3>
      <%=render "other_meeting_form"%>
   </div>
</div>

<script type="text/javascript">
    // $('#name-search-autocomplete').bind('railsAutocomplete.select', function(event, data){

        // event.preventDefault();
        // $('#new_clients_sitting').submit();

    // });
</script>

app/views/meetings/show_other.html.erb
<div class="container-fluid">
   <div class="row col-xs-12">
      <div id= "links" class="actions">
         <div>
            <%= button_to('New Activity', meetings_new_other_meeting_path, :class => 'btn btn-primary pull-right btn-padded')  %>
         </div>
      </div>
   </div>
   <div class="row col-xs-12">
      <table class="table table-hover table-condensed">
         <thead>
            <tr class="noborder">
               <th colspan="5"><h3>View Meetings</h3></th>
            </tr>
            <tr>
               <th>Client Name</th>
               <th>Date</th>
               <th>Case Manager</th>
               <th>Activity</th>
               <th>Duration</th>
               <th>Edit</th>
               <th>Delete</th>
            </tr>
         </thead>
            <% @other_meetings.each do |meeting| %>
            <tr>
               <td id="name">
                  <% if meeting.last_name != nil %>
                  <%=meeting.first_name + " " + meeting.last_name%>
                  <%else %>
                  <%=meeting.first_name%>
                  <%end%>
               </td>
               <td>
                  <% if meeting.start_date != nil %>
                     <%=meeting.start_date%>
                  <%end%>
               </td>
               <td>
                  <% if meeting.manager_id != nil %>
                     <%=Manager.find(meeting.manager_id).first_name%>
                  <%end%>
               </td>
               <td>
                  <% if meeting.meeting_type_id != nil %>
                     <%=MeetingType.find(meeting.meeting_type_id).name%>
                  <%end%>
               </td>
               <td>
                  <% if meeting.duration != nil %>
                     <%=meeting.duration%>
                  <%end%>
               </td>
               <td>
                  <%= button_to('Edit', "#{meeting.id}/edit_other_meeting", :class => 'btn btn-secondary btn-sm')%>
               </td>
               <td>
                  <%= button_to('Delete', "/meetings/#{meeting.id}/delete_other_meeting", :method => :delete,
                      data: { confirm: 'Are you sure?' }, :class => 'btn btn-secondary btn-sm')%>
               </td>
            </tr>
          <%end%>
      </table>
   </div>
</div>