config/routes.rb
Rails.application.routes.draw do


  get '/home' => 'sittings#select_sitting'
   # post '/home' => 'sittings#select_sitting'

  mount Upmin::Engine => '/admin'

  devise_for :users, :controllers => { registrations: 'users/registrations' }

  # devise_scope :user do
  # 	root :to => "devise/sessions#new"
  # end

  devise_scope :user do
    authenticated :user do
      root 'sittings#select_sitting', as: :authenticated_root
      # match '/sessions/user', to: 'devise/sessions#create', via: :post
    end

    unauthenticated do
      # root 'devise/sessions#new', as: :unauthenticated_root
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

 # users
  get "users/new" => "users#new", as: :users_new_user
  post "users/create_user" => "users#create", as: :users_create_user
  get "users/:id/edit" => "users#edit", as: :users_edit_user
  put "users/:id" => "users#update", as: :users_update_user

 # calendars/google authenication
  resources :calendars
  get "/auth/:provider/callback" => 'calendars#create'
  post "/calendars" => 'calendars#new'

  #sittings

  get '/sittings/refresh' => 'sittings#refresh'
  post '/sittings/refresh' => 'sittings#refresh'
  # get '/sittings/create_calendar'  => 'sittings#create_calendar'
  get '/sittings/update_calendar'  => 'sittings#update_calendar'
  get '/sittings/select_sitting'  => 'sittings#select_sitting'
  post '/sittings/select_sitting'  => 'sittings#select_sitting'
  post '/sittings/update_sitting' => 'sittings#update_sitting'
  get '/sittings/update_sitting' => 'sittings#update_sitting'
  post '/sittings/update' => 'sittings#update'
  post '/sittings/view_past_sittings' => 'sittings#view_past_sittings'
  get '/sittings/view_past_sittings' => 'sittings#view_past_sittings'


  #clients
  delete '/clients/:clients_sittings_id/cancel_attendance' => 'clients#cancel_attendance'
  post '/clients/attendance/' => 'clients#attendance'
  get '/clients/attendance', to:'clients#attendance'
  get '/clients/list_all' => 'clients#list_all'
  post '/clients/list_all' => 'clients#list_all'
  post '/clients/update_list_all_client' => 'clients#update_list_all_client'
  post '/clients/update_clients_sitting_autocomplete' => 'clients#update_clients_sitting_autocomplete'
  post '/clients/update_client_status' => 'clients#update_client_status'
  get '/clients/autocomplete', to: 'clients#autocomplete', as: 'autocomplete_client'
  # post '/clients/js_add_client_to_sitting', to: 'clients#js_add_client_to_sitting'
  get 'clients/home' => 'clients#home'
  get '/clients/schedule_meetings' => 'clients#schedule_meetings'
  post '/clients/schedule_meetings' => 'clients#schedule_meetings'
  get '/clients/:group_id/new_dropdown' =>'clients#new_dropdown'
  post '/clients/new_dropdown' =>'clients#new_dropdown'
  get '/clients/manage_clients' => 'clients#manage_clients'
  post '/clients/manage_clients' => 'clients#manage_clients'
  get '/clients/manage_inactive_clients' => 'clients#manage_inactive_clients'
  post '/clients/manage_inactive_clients' => 'clients#manage_inactive_clients'
  get '/clients/manage_absent_clients' => 'clients#manage_absent_clients'
  post '/clients/manage_absent_clients' => 'clients#manage_absent_clients'
  post '/clients/new' => 'clients#new'
  get  'clients/:id/history' => 'clients#history'
  post '/clients/:id/history' => 'clients#history'
  post '/clients/:id/edit' => 'clients#edit'
  post '/clients/:id/update' => 'clients#update'
  patch '/clients/:id/update' => 'clients#update'
  get '/clients/update' => 'clients#update'
  post '/clients/update' => 'clients#update'

  #special_status
  get '/clients/:client_id/new_special_status' => 'clients#new_special_status'
  post '/clients/update_special_status' => 'clients#update_special_status'

  #location
  post '/clients/update_location_status' => 'clients#update_location_status'

  #meetings
  post '/meetings/:meeting_id/delete_other_meeting' => 'meetings#delete_other_meeting'
  delete '/meetings/:meeting_id/delete_other_meeting' => 'meetings#delete_other_meeting'
  post '/meetings/:meeting_id/edit_other_meeting' => 'meetings#edit_other_meeting'
  get '/meetings/:meeting_id/edit_other_meeting' => 'meetings#edit_other_meeting'
  get '/meetings/:client_id/new' => 'meetings#new'
  post '/meetings/update' => 'meetings#update'
  delete '/meetings/:meeting_id/destroy' => 'meetings#destroy'
  post '/meetings/new_other_meeting' => 'meetings#new_other_meeting'
  get '/meetings/new_other_meeting' => 'meetings#new_other_meeting'
  get '/meetings/autocomplete', to: 'meetings#autocomplete', as: 'autocomplete_meeting'
  get '/meetings/show_other' => 'meetings#show_other'
  post '/meetings/show_other' => 'meetings#show_other'

  #groups
  delete '/groups/:clients_groups_id/delete_clients_groups' => 'groups#delete_clients_groups'
  delete '/groups/:id/delete_group' => 'groups#delete_group'
  get '/groups/:id/all_clients_in_group' => 'groups#all_clients_in_group'
  post '/groups/manage_groups' => 'groups#manage_groups'
  get '/groups/manage_groups' => 'groups#manage_groups'
  post '/groups/update_clients_in_group' => 'groups#update_clients_in_group'
  post '/groups/new' => 'groups#new'
  post '/groups/:id/edit' => 'groups#edit'
  get '/groups/:id/update' => 'groups#update'
  post '/groups/:id/update' => 'groups#update'
  patch '/groups/:id/update' => 'groups#update'
  get '/groups/update' => 'groups#update'
  post '/groups/update' => 'groups#update'

  #notes
  post '/notes/new' => 'notes#new'
  get '/notes/update' => 'notes#update'
  post '/notes/update' => 'notes#update'
  post '/notes/:id/edit' => 'notes#edit'
  delete '/notes/:id/destroy' => 'notes#destroy'

  #reports
  get 'reports/generate_reports' => 'reports#generate_reports'
  post 'reports/generate_reports' => 'reports#generate_reports'
  post 'reports/new' => 'reports#new'
  get 'reports/attendance_report' => 'reports#attendance_report'
  post 'reports/attendance_report' => 'reports#attendance_report'
  get 'reports/meeting_report' => 'reports#meeting_report'
  post 'reports/meeting_report' => 'reports#meeting_report'
  get 'reports/client_report' => 'reports#client_report'
  post 'reports/client_report' => 'reports#client_report'


  # resources :sessions
  # resources :users
  resources :reports
  resources :clients
  resources :meetings
  resources :monastics
  resources :sittings
  resources :clients_sittings
  resources :attendance_status_types
  resources :groups
  resources :notes

  get '/visitors/instructions' => 'visitors#instructions'

end

app/models/user.rb
class User < ActiveRecord::Base
  
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, 
  :trackable, :validatable, :registerable
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def new
    flash[:failure] = "Registration is not allowed."
    redirect_to '/'
  end












	protected

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  # before_filter :admin_only, :except => :show

  def index
    @users = User.all
  end

  def new
    @user = User.new
    respond_to do |format|
      format.json { render :json => @user }   
      format.xml  { render :xml => @user }
      format.html
    end
  end

  def create
    @user = User.new(secure_params_new)
    #@user.user! #set role to type :user
    if @user.save
      respond_to do |format|
        format.json { render :json => @user.to_json, :status => 200 }
        format.xml  { head :ok }
        format.html { redirect_to :action => :index }
      end
    else
      respond_to do |format|
        format.json { render :text => "Could not create user", :status => :unprocessable_entity } # placeholder
        format.xml  { head :ok }
        format.html { render :action => :new, :status => :unprocessable_entity }
      end
    end
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    respond_to do |format|
      format.json { render :json => @user }   
      format.xml  { render :xml => @user }
      format.html
    end
 
  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params_new)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private
    def admin_only
      unless current_user.admin?
        redirect_to :back, :alert => "Access denied."
      end
    end

    def secure_params
      params.require(:user).permit(:role)
    end

    def secure_params_new
      params.require(:user).permit(:email,:password, :password_confirmation,:role)
    end 
end

app/views/users/_form_new.html.erb
<%= form_for(@user, :url => users_create_user_path) do |f| %>
   <% if @user.errors.any? %>
      <div id="error_explanation">
         <h2><%= pluralize(@user.errors.count, "error") %> could not register the new user:</h2>
         <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
         </ul>
      </div>
    <% end %>
   <div class="form-group">
      <p><%= f.label :email %></p>
      <p><%= f.email_field :email ,class: 'form-control' %></p>
   </div>
   <div class="form-group">
      <p><%= f.label :password %></p>
      <p><%= f.password_field :password, class: 'form-control' %></p>
   </div>
   <div class="form-group">
      <p><%= f.label :password_confirmation %></p>
      <p><%= f.password_field :password_confirmation, class: 'form-control' %></p>
   </div>
   <div class="form-group">
      <p><%= f.label :role %></p>
      <p><%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}, class: 'form-control') %></p>
   </div>
   <p><%= f.submit "Add User", class:"btn btn-primary"    %></p>
<% end %>

app/views/users/_form_update.html.erb
<%= form_for(@user, :url => users_update_user_path) do |f| %>
   <%if @user.errors.any? %>
      <div id="error_explanation">
         <h2><%= pluralize(@user.errors.count, "error") %> could not register the new user:</h2>
         <ul>
            <% @user.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
            <% end %>
         </ul>
      </div>
   <% end %>
   <div class="form-group">
      <p><%= f.label :email %></p>
      <p><%= f.email_field :email ,class: 'form-control' %></p>
   </div>
   <div class="form-group">
      <p><%= f.label :password %></p>
      <p><%= f.password_field :password, class: 'form-control' %></p>
   </div>
   <div class="form-group">
      <p><%= f.label :password_confirmation %></p>
      <p><%= f.password_field :password_confirmation, class: 'form-control' %></p>
   </div>
   <div class="form-group">
      <p><%= f.label :role %></p>
      <p><%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}, class: 'form-control') %></p>
   </div>
      <p><%= f.submit "Update User", class:"btn btn-primary"    %></p>
<% end %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<!-- <td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td> -->
<td>
	<%= link_to "Edit", edit_user_path(user), class: 'button-xs' %>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/edit.html.erb
<div class="authform">
   <h4>Edit User</h4>
   <%= render 'form_update' %>
</div>

app/views/users/index.html.erb
<div class="container">
   <div class="row">
      <br/>
      <%= link_to 'New User', users_new_user_path ,class:"btn btn-primary" %> <br/><br/>
   <h3>Users</h3>
      <div class="column">
      <table class="table">
         <tbody>
            <% @users.each do |user| %>
            <tr>
               <%= render user %>
            </tr>
            <% end %>
         </tbody>
      </table>
      </div>
   </div>
</div>

app/views/users/new.html.erb
<div class="authform">
    <h4>Add User</h4>
    <%= render 'form_new' %>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>