config/routes.rb
Rails.application.routes.draw do


  get '/home' => 'sittings#select_sitting'
   # post '/home' => 'sittings#select_sitting'

  mount Upmin::Engine => '/admin'

  devise_for :users, :controllers => { registrations: 'users/registrations' }

  # devise_scope :user do
  # 	root :to => "devise/sessions#new"
  # end

  devise_scope :user do
    authenticated :user do
      root 'sittings#select_sitting', as: :authenticated_root
      # match '/sessions/user', to: 'devise/sessions#create', via: :post
    end

    unauthenticated do
      # root 'devise/sessions#new', as: :unauthenticated_root
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

 # users
  get "users/new" => "users#new", as: :users_new_user
  post "users/create_user" => "users#create", as: :users_create_user
  get "users/:id/edit" => "users#edit", as: :users_edit_user
  put "users/:id" => "users#update", as: :users_update_user

 # calendars/google authenication
  resources :calendars
  get "/auth/:provider/callback" => 'calendars#create'
  post "/calendars" => 'calendars#new'

  #sittings

  get '/sittings/refresh' => 'sittings#refresh'
  post '/sittings/refresh' => 'sittings#refresh'
  # get '/sittings/create_calendar'  => 'sittings#create_calendar'
  get '/sittings/update_calendar'  => 'sittings#update_calendar'
  get '/sittings/select_sitting'  => 'sittings#select_sitting'
  post '/sittings/select_sitting'  => 'sittings#select_sitting'
  post '/sittings/update_sitting' => 'sittings#update_sitting'
  get '/sittings/update_sitting' => 'sittings#update_sitting'
  post '/sittings/update' => 'sittings#update'
  post '/sittings/view_past_sittings' => 'sittings#view_past_sittings'
  get '/sittings/view_past_sittings' => 'sittings#view_past_sittings'


  #clients
  delete '/clients/:clients_sittings_id/cancel_attendance' => 'clients#cancel_attendance'
  post '/clients/attendance/' => 'clients#attendance'
  get '/clients/attendance', to:'clients#attendance'
  get '/clients/list_all' => 'clients#list_all'
  post '/clients/list_all' => 'clients#list_all'
  post '/clients/update_list_all_client' => 'clients#update_list_all_client'
  post '/clients/update_clients_sitting_autocomplete' => 'clients#update_clients_sitting_autocomplete'
  post '/clients/update_client_status' => 'clients#update_client_status'
  get '/clients/autocomplete', to: 'clients#autocomplete', as: 'autocomplete_client'
  # post '/clients/js_add_client_to_sitting', to: 'clients#js_add_client_to_sitting'
  get 'clients/home' => 'clients#home'
  get '/clients/schedule_meetings' => 'clients#schedule_meetings'
  post '/clients/schedule_meetings' => 'clients#schedule_meetings'
  get '/clients/:group_id/new_dropdown' =>'clients#new_dropdown'
  post '/clients/new_dropdown' =>'clients#new_dropdown'
  get '/clients/manage_clients' => 'clients#manage_clients'
  post '/clients/manage_clients' => 'clients#manage_clients'
  get '/clients/manage_inactive_clients' => 'clients#manage_inactive_clients'
  post '/clients/manage_inactive_clients' => 'clients#manage_inactive_clients'
  get '/clients/manage_absent_clients' => 'clients#manage_absent_clients'
  post '/clients/manage_absent_clients' => 'clients#manage_absent_clients'
  post '/clients/new' => 'clients#new'
  get  'clients/:id/history' => 'clients#history'
  post '/clients/:id/history' => 'clients#history'
  post '/clients/:id/edit' => 'clients#edit'
  post '/clients/:id/update' => 'clients#update'
  patch '/clients/:id/update' => 'clients#update'
  get '/clients/update' => 'clients#update'
  post '/clients/update' => 'clients#update'

  #special_status
  get '/clients/:client_id/new_special_status' => 'clients#new_special_status'
  post '/clients/update_special_status' => 'clients#update_special_status'

  #location
  post '/clients/update_location_status' => 'clients#update_location_status'

  #meetings
  post '/meetings/:meeting_id/delete_other_meeting' => 'meetings#delete_other_meeting'
  delete '/meetings/:meeting_id/delete_other_meeting' => 'meetings#delete_other_meeting'
  post '/meetings/:meeting_id/edit_other_meeting' => 'meetings#edit_other_meeting'
  get '/meetings/:meeting_id/edit_other_meeting' => 'meetings#edit_other_meeting'
  get '/meetings/:client_id/new' => 'meetings#new'
  post '/meetings/update' => 'meetings#update'
  delete '/meetings/:meeting_id/destroy' => 'meetings#destroy'
  post '/meetings/new_other_meeting' => 'meetings#new_other_meeting'
  get '/meetings/new_other_meeting' => 'meetings#new_other_meeting'
  get '/meetings/autocomplete', to: 'meetings#autocomplete', as: 'autocomplete_meeting'
  get '/meetings/show_other' => 'meetings#show_other'
  post '/meetings/show_other' => 'meetings#show_other'

  #groups
  delete '/groups/:clients_groups_id/delete_clients_groups' => 'groups#delete_clients_groups'
  delete '/groups/:id/delete_group' => 'groups#delete_group'
  get '/groups/:id/all_clients_in_group' => 'groups#all_clients_in_group'
  post '/groups/manage_groups' => 'groups#manage_groups'
  get '/groups/manage_groups' => 'groups#manage_groups'
  post '/groups/update_clients_in_group' => 'groups#update_clients_in_group'
  post '/groups/new' => 'groups#new'
  post '/groups/:id/edit' => 'groups#edit'
  get '/groups/:id/update' => 'groups#update'
  post '/groups/:id/update' => 'groups#update'
  patch '/groups/:id/update' => 'groups#update'
  get '/groups/update' => 'groups#update'
  post '/groups/update' => 'groups#update'

  #notes
  post '/notes/new' => 'notes#new'
  get '/notes/update' => 'notes#update'
  post '/notes/update' => 'notes#update'
  post '/notes/:id/edit' => 'notes#edit'
  delete '/notes/:id/destroy' => 'notes#destroy'

  #reports
  get 'reports/generate_reports' => 'reports#generate_reports'
  post 'reports/generate_reports' => 'reports#generate_reports'
  post 'reports/new' => 'reports#new'
  get 'reports/attendance_report' => 'reports#attendance_report'
  post 'reports/attendance_report' => 'reports#attendance_report'
  get 'reports/meeting_report' => 'reports#meeting_report'
  post 'reports/meeting_report' => 'reports#meeting_report'
  get 'reports/client_report' => 'reports#client_report'
  post 'reports/client_report' => 'reports#client_report'


  # resources :sessions
  # resources :users
  resources :reports
  resources :clients
  resources :meetings
  resources :monastics
  resources :sittings
  resources :clients_sittings
  resources :attendance_status_types
  resources :groups
  resources :notes

  get '/visitors/instructions' => 'visitors#instructions'

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  require 'date'

  def home
    if session[:sitting_id] != nil
      respond_to do |format|
        format.html { redirect_to("/clients/attendance") }
      end
    else
      respond_to do |format|
        format.html { redirect_to("/sittings/select_sitting") }
      end
    end
  end

  #STUDENT ROUTES
  def attendance
    @sitting_id = session[:sitting_id]
    @sitting = Sitting.find(@sitting_id)
    @sitting_event_title = Sitting.find(@sitting_id).event_title
    @sitting_start_date = Sitting.find(@sitting_id).start_date.strftime("%A, %B %-d, %Y")
    @attendance_status_type_id_scheduled = AttendanceStatusType.where(name: "scheduled").first.id
    @attendance_status_type_id_present = AttendanceStatusType.where(name: "present").first.id
    @scheduled_clients = Client.select('clients.id, clients.senority, clients.first_name, clients.last_name, special_status_types.name AS special_status, clients_sittings.id AS clients_sittings_id, clients_sittings.hatto AS hatto, category_types.name AS category_name, category_types.order AS category_order').joins('
      INNER JOIN clients_sittings ON clients_sittings.client_id = clients.id
      INNER JOIN attendance_status_types ON attendance_status_types.id = clients_sittings.attendance_status_type_id
      LEFT OUTER JOIN special_status_types ON special_status_types.id = clients_sittings.special_status_type_id
      LEFT OUTER JOIN category_types ON category_types.id = clients.category_type_id'
      ).where("
      clients_sittings.attendance_status_type_id =? AND clients_sittings.sitting_id =?", @attendance_status_type_id_scheduled, @sitting_id).order("category_types.order ASC").order(:senority).order(:first_name)
    @attending_clients = Client.select('clients.id, clients.first_name, clients.last_name, clients.senority, special_status_types.name AS special_status, clients_sittings.id AS clients_sittings_id, clients_sittings.meeting_id AS meeting_id, clients_sittings.hatto AS hatto, category_types.name AS category_name, category_types.order AS category_order').joins('
      INNER JOIN clients_sittings ON clients_sittings.client_id = clients.id
      INNER JOIN attendance_status_types ON attendance_status_types.id = clients_sittings.attendance_status_type_id
      LEFT OUTER JOIN special_status_types ON special_status_types.id = clients_sittings.special_status_type_id
      LEFT OUTER JOIN category_types ON category_types.id = clients.category_type_id'
      ).where("
      clients_sittings.attendance_status_type_id =? AND clients_sittings.sitting_id =?", @attendance_status_type_id_present, @sitting_id).order("category_types.order ASC").order(:senority).order(:first_name)

    @clients = Client.all
    @clients_sittings = ClientsSitting.new
    @clients_sittings_loc = ClientsSitting.new
    @all_groups = Group.all
    @clients_groups = ClientsGroup.new
    @note = Note.new
    @current_note = Note.where(id:@sitting.note_id).first

  end

  def autocomplete
    @clients = Client.search_by_name(params[:term]).active_client
    render json: @clients, root: false, each_serializer: AutocompleteSerializer
  end

  def update_clients_sitting_autocomplete
   clients_sitting = ClientsSitting.where(sitting_id:params[:clients_sitting][:sitting_id],client_id:params[:clients_sitting][:client_id]).first_or_initialize
    respond_to do |format|
      if (clients_sitting.update(clients_sitting_params))
        format.html { redirect_to("/clients/attendance") }
      else
        format.html { redirect_to("/clients/attendance") }
      end
    end
  end

  def list_all
    @sitting_id = session[:sitting_id]
    @clients = Client.active_client.order(:first_name)
    @clients_sittings = ClientsSitting.new
    @attendance_status_type_id_present = AttendanceStatusType.where(name: "present").first.id
    @attendance_status_type_id_scheduled = AttendanceStatusType.where(name: "scheduled").first.id
  end

  def cancel_attendance
     clients_sittings = ClientsSitting.find(params[:clients_sittings_id])
     clients_sittings.destroy
   respond_to do |format|
      format.html { redirect_to '/clients/attendance' }
      format.json
      format.js
   end
  end

  def schedule_meetings
    @sitting_id = session[:sitting_id]
    @sitting = Sitting.find(@sitting_id)
    @current_note = Note.where(id:@sitting.note_id).first
    @sitting_event_title = Sitting.find(@sitting_id).event_title
    @sitting_start_date = Sitting.find(@sitting_id).start_date.strftime("%A, %B %-d, %Y")
    @attendance_status_type_id_scheduled = AttendanceStatusType.where(name: "scheduled").first.id
    @attendance_status_type_id_present = AttendanceStatusType.where(name: "present").first.id
    @attending_clients_search = Client.joins('
      INNER JOIN clients_sittings ON clients_sittings.client_id = clients.id
      INNER JOIN attendance_status_types ON attendance_status_types.id = clients_sittings.attendance_status_type_id'
      ).where("
      clients_sittings.attendance_status_type_id =? AND clients_sittings.sitting_id =?",
    @attendance_status_type_id_present, @sitting_id).order("days_since_last_seen DESC")
    @attending_clients_search.each do |s|
      s.calc_last_seen(@sitting_id,s)
    end
    @attending_clients = Client.select('clients.id, clients.first_name, clients.last_name, clients.bench, clients.acceptance_date, clients.date_last_seen, clients.days_since_last_seen, special_status_types.name AS special_status, special_status_types.priority AS special_status_priority, clients_sittings.sitting_id AS sitting_id, clients_sittings.meeting_id AS meeting_id, clients_sittings.hatto AS hatto, category_types.name AS category_name').joins('
      INNER JOIN clients_sittings ON clients_sittings.client_id = clients.id
      INNER JOIN attendance_status_types ON attendance_status_types.id = clients_sittings.attendance_status_type_id
      LEFT OUTER JOIN special_status_types ON special_status_types.id = clients_sittings.special_status_type_id
      LEFT OUTER JOIN category_types ON category_types.id = clients.category_type_id'
      ).where("
      clients_sittings.attendance_status_type_id =? AND clients_sittings.sitting_id =?",
    @attendance_status_type_id_present, @sitting_id).where("category_types.name !=? AND category_types.name !=?","Formal", "Manager").order("special_status_types.priority DESC").order("days_since_last_seen DESC").order(:first_name)
    @attending_managers = Client.select('clients.id, clients.first_name, clients.last_name, clients.bench, clients.acceptance_date, clients.date_last_seen, clients.days_since_last_seen, clients.senority, special_status_types.name AS special_status, clients_sittings.sitting_id AS sitting_id, clients_sittings.meeting_id AS meeting_id, clients_sittings.hatto AS hatto, category_types.name AS category_name').joins('
      INNER JOIN clients_sittings ON clients_sittings.client_id = clients.id
      INNER JOIN attendance_status_types ON attendance_status_types.id = clients_sittings.attendance_status_type_id
      LEFT OUTER JOIN special_status_types ON special_status_types.id = clients_sittings.special_status_type_id
      LEFT OUTER JOIN category_types ON category_types.id = clients.category_type_id'
      ).where("
      clients_sittings.attendance_status_type_id =? AND clients_sittings.sitting_id =?",
      @attendance_status_type_id_present, @sitting_id).where("category_types.name =? OR category_types.name =?","Formal", "Manager").order(:senority)
  end

  def admin
  end

  def new_dropdown
    @sitting_id = session[:sitting_id]
    @attendance_status_type_id_scheduled = AttendanceStatusType.where(name: "scheduled").first.id
    @group = Group.find(params[:clients_group][:group_id])
    @clients_in_groups = Client.select('clients.id, clients.first_name, clients.last_name, clients_groups.id AS clients_groups_id, groups.name AS group_name, category_types.name AS category_name').joins('
    INNER JOIN clients_groups ON clients_groups.client_id = clients.id
    INNER JOIN groups ON clients_groups.group_id = groups.id
    LEFT OUTER JOIN category_types ON category_types.id = clients.category_type_id'
    ).where("
    groups.id =?", @group.id)
    @clients_sittings = ClientsSitting.new
    @clients = Client.all
    if (@clients_in_groups.each != nil) then
      @clients_in_groups.each do |client|
        @clients_sitting_entry = ClientsSitting.where(sitting_id:@sitting_id, client_id:client.id).first_or_initialize do |ss|
            ss.attendance_status_type_id = @attendance_status_type_id_scheduled
        end
         @clients_sitting_entry.save
      end
    end
    respond_to do |format|
      format.html { redirect_to("/clients/attendance")}
    end
  end

  def update_client_status
    @clients_sittings = ClientsSitting.where(sitting_id:params[:clients_sitting][:sitting_id],client_id:params[:clients_sitting][:client_id]).first_or_initialize
    respond_to do |format|
      if (@clients_sittings.update(clients_sitting_params))
        format.html { redirect_to '/clients/attendance' }
        format.json
        format.js
      else
        format.html { redirect_to("/clients/attendance")}
      end
    end
  end

  def update_location_status
    @clients_sittings_loc = ClientsSitting.where(sitting_id:params[:clients_sitting][:sitting_id],client_id:params[:clients_sitting][:client_id]).first_or_initialize
    respond_to do |format|
      if (@clients_sittings_loc.update(clients_sitting_params))
        format.html { redirect_to '/clients/attendance' }
        format.json
        format.js
      else
        format.html { redirect_to("/clients/attendance")}
      end
    end
  end

  def update_list_all_client
    @clients_sitting = ClientsSitting.where(sitting_id:params[:clients_sitting][:sitting_id],client_id:params[:clients_sitting][:client_id]).first_or_initialize
    respond_to do |format|
      if (@clients_sitting.update(clients_sitting_params))
        format.html { redirect_to("/clients/list_all") }

app/helpers/clients_helper.rb
module ClientsHelper

  def display_name

    @client = Client.find(@client_id)

    if @client.last_name != nil
      @client.first_name.capitalize + " " + @client.last_name.capitalize
    else
      @client.first_name
    end

  end

  # def client_category

  #   if client.category_name != nil
  #       (client.category_name[0,1])
  #   end

  # end

end

app/views/clients/attendance.html.erb
<div class="container-fluid nopadding">
	<div class="col-xs-12">
      <h2>Record Attendance</h2>
   </div>
   <div class="col-xs-12">
		<div class="panel panel-default">
      	<div class="panel-heading" id="light-blue">
	         <h4 class="panel-title" id="blue-text"><%=@sitting_event_title + " - " + @sitting_start_date%></h4>
      	</div>
      	<div class="panel-body">
            <%if @current_note != nil %>
				<p><%=@current_note.content%></p>
			   <div class="prev">
				  <%= button_to('Edit', edit_note_path(@current_note.id), :class => 'btn btn-secondary btn-grey-padded btn-sm pull-right')%>
			   </div>
			   <div class="next">
				   <%= button_to('Delete', "/notes/#{@current_note.id}/destroy",
					:method => :delete,
                    data: { confirm: 'Are you sure?' }, :class => 'btn btn-secondary btn-sm pull-right')%>
            </div>
			      <%else%>
			         <%= button_to('New Note', new_note_path, :class => 'btn btn-secondary btn-grey-padded btn-md pull-right')%>
			      <%end%>
         </div>
		 </div>
	</div>
	<div class="col-xs-12">
		<%= button_to('View all clients', clients_list_all_path, :class => 'btn btn-secondary btn-grey-padded btn-md pull-right')%>
	</div>
	<div class="col-xs-12">
	 	<div class="panel panel-default">
      	<div class="col-xs-12 panel-heading" id="light-blue">
        	<div class="col-xs-12 col-sm-6">
		 		<%= form_for(@clients_groups, :url => {:action => "new_dropdown"}, :html => {
                     :class =>"select_client_group_form"} ) do |f| %>
		 		   <%= f.label "Select group", :class => "select_client_group_form"%>
		         <%= f.collection_select(:group_id, Group.all, :id, :name)%><br />
		      <div id= "buttonId" class="actions">
		         <%= f.submit "Submit", class:"btn btn-secondary btn-md" %>
		      </div>
		      <%end%>
			</div>
			<div class="col-xs-12 col-sm-6">
				<%= form_for(@clients_sittings, :url => {:action => "update_clients_sitting_autocomplete"}, :html => {
                     :class =>"select_client_group_form"}) do |f| %>
					<div class="field">
					<%= f.label "Search for clients" %>
					<%= autocomplete_field_tag('Name', '', autocomplete_client_path, :id_element => "#clients_sitting_client_id", class: "form-control", id:"name-search-autocomplete") %>
					<%= f.hidden_field :sitting_id, :value => @sitting_id %>
					<%= f.hidden_field :client_id %>
					<%= f.hidden_field :attendance_status_type_id, :value => @attendance_status_type_id_present%>
					</div>
				<%end%>
			</div>
			</div>
		<!-- EXPECTED STUDENTS -->
	         <table class="table table-condensed" id="scheduled-table">
				<thead>
					<tr class="noborder">
						<th colspan="4"><h3>Expected clients</h3></th>
					</tr>
					<tr>
						<th class="norm">Name</th>
						<th id="td-align" class="norm">Change attendance</th>
						<th id="td-align" class="norm"></th>
					</tr>
				</thead>
						<% @scheduled_clients.each do |client| %>
					<tr>
						<td class="norm">
                     <div>
                        <% if client.last_name != nil %>
                        <%=client.first_name + " " + client.last_name%>
                        <%else %>
                        <%=client.first_name%>
                        <%end%>
                     </div>
                  </td>
						<td>
						<div id="center">
							<div class="btn-group" role="group">
							<%= form_for(@clients_sittings, :url => {:action => "update_client_status"}, remote: true) do |f| %>
                        <%= f.hidden_field :sitting_id, :value => @sitting_id %>
                         	<%= f.hidden_field :client_id, :value => client.id %>
                        <%= f.hidden_field :attendance_status_type_id, :value => @attendance_status_type_id_present%>
                        <div id="scheduled_btn" class="btn">
                          <%= button_tag(type: 'submit', class: "btn btn-default btn-xs update_client_status test23") do %>
                              <i class="glyphicon glyphicon-ok"></i>
                          <%end%>
                        </div>
                        <%end%>
                           <div id="scheduled_btn" class="btn">
                              <%=link_to "/clients/#{client.clients_sittings_id}/cancel_attendance", :method => :delete, :remote =>:true, class: "btn btn-default btn-xs cancel_attendance" do %>
                                 <i class="glyphicon glyphicon-remove"></i>
                              <%end%>
                           </div>
		              		</div>
		              	</div>
		              	</td>
		              	<td id="td-align"></td>
		            </tr>
		             	<%end%>
		        </table>

		<!-- ATTENDING STUDENTS -->
				<table class="table table-condensed" id="attending-table">
				<thead>
					<tr>
						<th colspan="5"><h3>Attending clients</h3></th>
					</tr>
					<tr>
						<th class="norm">Name</th>
						<th id="th-align" class="norm">Notes</th>
                        <th id="th-align" class="norm">Hatto</th>
						<th id="td-align" class="norm">Remove</th>
					</tr>
				</thead>
					<% @attending_clients.each do |client| %>
                  <tr>
                     <td class="norm">
                        <% if client.last_name != nil %>
                        <%=client.first_name + " " + client.last_name%>
                        <%else %>
                        <%=client.first_name%>
               <%end%>
                     <td id="td-align norm">
                        <div id="center">
                           <div class="btn-group" role="group">
                              <div id="btn-correction" class="btn btn-xs disabled">
                                 <% if client.special_status != nil%>
                                    <%=client.special_status%>
                                 <%end%>
                              </div>
                           </div>
                           <div id="scheduled_btn" class="btn">
                              <%=link_to "/clients/#{client.id}/new_special_status", class:"btn btn-default btn-xs" do%>
                                 <i class="glyphicon glyphicon-edit"></i>
                              <%end%>
                           </div>
                        </div>
                     </td>
                     <td id="td-align norm">
                        <div id="center">
                           <%= form_for(@clients_sittings_loc, :url => {:action => "update_location_status"}, :html => {:class => "loctype"}, remote: true) do |f| %>

                              <%= f.hidden_field :sitting_id, :value => @sitting_id %>
                              <%= f.hidden_field :client_id, :value => client.id %>

                           <div id="scheduled_btn" class="btn">
                              <%
                              @clients_sittings_check = ClientsSitting.where(sitting_id:@sitting_id,client_id:client.id).first_or_initialize
                              if @clients_sittings_check.hatto == true%>
                               <%= f.check_box :hatto, options = {:checked => true, :class => "checkbox"} %>
                              <%else%>
                               <%= f.check_box :hatto, options = {:checked => false, :class => "checkbox"} %>
                              <%end%>
                           </div>
                           <%end%>
                        </div>
                     </td>
                     <td id="td-align">
                        <%=link_to "/clients/#{client.clients_sittings_id}/cancel_attendance", :method => :delete, :remote => true, class:"btn btn-default btn-xs cancel_attendance" do %>
                           <i class="glyphicon glyphicon-remove"></i>
                        <%end%>
                     </td>
                     <%end%>
                  </tr>
			</table>
		</div>
	</div>

	<div id="links" class="row col-xs-12">
		<%= button_to('Done', clients_schedule_meetings_path, :class => 'btn btn-primary btn-padded pull-right')%>
	</div>
</div>

<script type="text/javascript">

	$('#name-search-autocomplete').bind('railsAutocomplete.select', function(event, data){

		// event.preventDefault();
		$('#new_clients_sitting').submit();

	});

    $(".test23").click(function(){
         $(this).closest('tr').addClass('selected_client_jquery').delay(2000).fadeOut(1);
    });

    // function delayedHide() {
    //     timeoutID = window.setTimeout(slowHide,2000)
    // }

    // function slowHide() {
    //     $(this).hide();
    // }

    $(function submitForm(){
        $('.checkbox').on('change',function(){
            $('.loctype').submit();
        });
    });


	// $(function(){
	// 	$('#team_id').bind('change', function () {
	// 	         var url = "/Teamleader/" + $(this).val()
	// 	          if (url) {
	// 	              window.location.replace(url);
	// 	          }
	// 	          return false;
	// 	      });
	// 	    });


	// $('#name-search-autocomplete').bind('railsAutocomplete.select', function(event, data){
	//   /* Do something here */
	//   // alert(data.item.id);

	//   //POST request - add client to sitting
	// var send_type = 'POST';
 //    var data_type = 'JSON';
 //    var send_data = {
 //        'sitting_id':$('#sitting_id').val(),
 //        'client_id':data.item.id,
 //    }

 //    var successFunc = function() {

 //    }

 //    $.ajax({
 //        type: send_type,
 //        url: '/clients/js_add_client_to_sitting',
 //        dataType: data_type,

 //        data: send_data,

 //        success: successFunc,
 //        error: function(jqXHR, textStatus, errorThrown) {

 //            if (window.DEBUG) {
 //                console.log("ajax error");
 //                console.log(jqXHR);
 //                console.log(textStatus);
 //                console.log(errorThrown);
 //            }

 //        }
 //    });//.ajax()



	// });

</script>

app/views/clients/cancel_attendance.js.erb
$('.cancel_attendance').bind('ajax:success', function() {
   $(this).closest('tr').addClass('unselected_client_jquery').delay(2000).fadeOut(1);
});

app/views/clients/draft.js.erb
// $("#client-table").append("<tr><%= escape_javascript(render 'all_client_entry') %></tr>");

app/views/clients/js_add_client_to_sitting.js.erb
// $("#<%= j 'verify_#{table_row_no}' %>").text("verified");

app/views/clients/manage_clients.html.erb
<div class="container-fluid">
   <div class="row col-xs-12">
      <div id= "links" class="actions">
         <div>
            <%= button_to('New Client', new_client_path, :class => 'btn  btn-primary pull-right btn-padded')  %>
         </div>

      </div>
   </div>
   <div class="row col-xs-8">
      <table class="table table-hover table-condensed">
         <thead>
            <tr class="noborder">
               <th colspan="5"><h3>Manage clients</h3></th>
            </tr>
            <tr>
               <th>Client Name</th>
               <th>Category</th>
               <th>Recent History</th>
               <th>Edit</th>
               <th>Delete</th>
            </tr>
         </thead>
            <% @clients.each do |client| %>
            <tr>
               <td id="name">
                  <% if client.last_name != nil %>
                     <%=client.first_name + " " + client.last_name%>
                  <%else %>
                     <%=client.first_name%>
                  <%end%>
               </td>
               <td>
                  <% if client.category_type.name != nil %>
                     <%=client.category_type.name%>
                  <%end%>
               </td>
               <td>
                  <%= button_to('Show History', "/clients/#{client.id}/history", :class => 'btn btn-secondary btn-sm')%>
               </td>
               <td><%= button_to('Edit', edit_client_path(client), :class => 'btn btn-secondary btn-sm')%>
               </td>
               <td><%= button_to 'Delete', client_path(client), :class => 'btn btn-secondary btn-sm',
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
               </td>
            </tr>
         <%end%>
      </table>
   </div>
   <div id= "links" class="actions col-xs-8">
   </div>
</div>

app/views/clients/update_client_status.js.erb
$("#attending-table").append("<tr><%= escape_javascript(render 'clients_sittings') %></tr>");

// alert("Clicked the button today Hannah");
// $(this).closest('tr').remove();

// $("#scheduled-table").on('click', '.update_client_status', function(event) {
//
//     });